server:
  port: 1000
spring:
  profiles:
    active: dev
  servlet:
   multipart:
     max-file-size: 100MB
     max-request-size: 1000MB

  jackson: # Jackson库配置
    date-format: "yyyy-MM-dd HH:mm:ss" # 设置日期格式为"年-月-日 时:分:秒"
    serialization:
      write-dates-as-timestamps: false # 关闭日期序列化为时间戳的功能
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#  配置sql日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # typeEnumsPackage or type-enums-package 都可以
  type-enums-package: com.project.platform.enums

resetPassword: 123456
